### ISSUE TITLE
Adding color-name-list as NPM dependency

### ISSUE THREAD

**Issue by meodai** [shariati/cherangi#1]
Hello! Great library. 

Thanks you for using my color name list <3. 

Because you need the Lab values for the colors, you keep a separate list I get why you keep your own list of color names. But it also means that your list is out of date quickly. So this would be my proposal:

add [color-name-list](https://github.com/meodai/color-names) as a dev dependency and have a rebuild package.json script or something that re-crates the static list. Maybe we can automate the recreation of the JS with a git hook or something.

ps: you don't have to convert the CSV to JSON (have a look at the dist folder ;) )

**Comment by shariati** [comment]
@meodai Thanks for your comment, I had this on my todo list. will be updating it by 29th September.
